name: "ci"

on:
    pull_request:
        branches:
            - "main"
    push:
        branches:
            - "main"

permissions: "read-all"

jobs:
    linux:
        runs-on: "ubuntu-latest"

        steps:
            -   name: "Checkout Code"
                uses: "actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608"
            -   name: "Setup Go"
                uses: "actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe"
                with:
                    go-version-file: "./go.mod"
            -   name: "Setup golangci-lint"
                uses: "golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc"
                with:
                    version: "latest"
            -   name: "Lint"
                run: "make lint"
            -   name: "Test"
                run: "make test"
