name: "ci"

on:
    pull_request:
        branches:
            - "main"
    push:
        branches:
            - "main"

permissions: "read-all"

jobs:
    linux:
        runs-on: "ubuntu-latest"

        steps:
            -   name: "Checkout Code"
                uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11"
            -   name: "Setup Go"
                uses: "actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe"
                with:
                    go-version-file: "./go.mod"
            -   name: "Setup golangci-lint"
                uses: "golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc"
                with:
                    version: "latest"
            -   name: "Lint"
                run: "make lint"
            -   name: "Test"
                run: "make test"
            -   name: "Build"
                uses: "goreleaser/goreleaser-action@3fa32b8bb5620a2c1afe798654bbad59f9da4906"
                with:
                    version: "latest"
                    args: "build --clean --snapshot"
