name: "release"

on:
    push:
        tags:
            - "*"

permissions: "read-all"

jobs:
    release:
        runs-on: "ubuntu-latest"

        permissions:
            contents: "write"

        steps:
            -   name: "Checkout Code"
                uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11"
                with:
                    fetch-depth: 0
            -   name: "Setup Go"
                uses: "actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491"
                with:
                    go-version-file: "./go.mod"
            -   name: "Release"
                uses: "goreleaser/goreleaser-action@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8"
                id: "release"
                with:
                    version: "latest"
                    args: "release --clean"
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
