name: "release"

on:
    push:
        tags:
            - "*"

permissions: "read-all"

jobs:
    release:
        runs-on: "ubuntu-latest"

        permissions:
            contents: "write"

        steps:
            -   name: "Checkout Code"
                uses: "actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744"
                with:
                    fetch-depth: 0
            -   name: "Setup Go"
                uses: "actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe"
                with:
                    go-version-file: "./go.mod"
            -   name: "Release"
                uses: "goreleaser/goreleaser-action@3fa32b8bb5620a2c1afe798654bbad59f9da4906"
                id: "release"
                with:
                    version: "latest"
                    args: "release --clean"
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
